In [15]:
import cvxpy as cp
import numpy as np

x=cp.Variable((10,10),boolean = True)
y=cp.Variable(10,nonneg=True)

#A=np.array([
#    [0,0.041,0.04,0.053,0.6,0.7,0.7,0.8,0.9,1.1],
#    [0.041,0,0.045,0.059,0.6,0.7,0.7,0.7,0.8,1.1],
#    [0.04,0.045,0,0.0136,0.6,0.6,0.6,0.6,0.8,1],
#    [0.053,0.059,0.0136,0,0.6,0.6,0.6,0.6,0.8,1],
#    [0.6,0.6,0.6,0.6,0,0.059,0.07,0.07,0.2,0.5],
#    [0.7,0.7,0.6,0.6,0.059,0,0.014,0.0185,0.1,0.4],
#    [0.7,0.7,0.6,0.6,0.07,0.014,0,0.06,0.2,0.5],
#    [0.8,0.7,0.6,0.6,0.07,0.0185,0.06,0,0.1,0.4],
#    [0.9,0.8,0.8,0.8,0.2,0.1,0.2,0.1,0,0.3],
#    [1.1,1.1,1,1,0.5,0.4,0.5,0.4,0.3,0]
#])

#obj_func = cp.sum(cp.multiply(A,x))

obj_func = 0.041*x[0,1]+0.04*x[0,2]+0.053*x[0,3]+0.6*x[0,4]+0.7*x[0,5]+0.7*x[0,6]+0.8*x[0,7]+0.9*x[0,8]+1.1*x[0,9]
+0.041*x[1,0]+0.045*x[1,2]+0.059*x[1,3]+0.6*x[1,4]+0.7*x[1,5]+0.7*x[1,6]+0.7*x[1,7]+0.8*x[1,8]
+1.1*x[1,9]+0.04*x[2,0]+0.045*x[2,1]+0.0136*x[2,3]+0.6*x[2,4]+0.6*x[2,5]+0.6*x[2,6]+0.6*x[2,7]+0.8*x[2,8]+1*x[2,9]
+0.053*x[3,0]+0.059*x[3,1]+0.0136*x[3,2]+0.6*x[3,4]+0.6*x[3,5]+0.6*x[3,6]+0.6*x[3,7]+0.8*x[3,8]+1*x[3,9]
+0.6*x[4,0]+0.6*x[4,1]+0.6*x[4,2]+0.6*x[4,3]+0.059*x[4,5]+0.07*x[4,6]+0.07*x[4,7]+0.2*x[4,8]+0.5*x[4,9]
+0.7*x[5,0]+0.7*x[5,1]+0.6*x[5,2]+0.6*x[5,3]+0.059*x[5,4]+0.014*x[5,6]+0.0185*x[5,7]+0.1*x[5,8]+0.4*x[5,9]
+0.7*x[6,0]+0.7*x[6,1]+0.6*x[6,2]+0.6*x[6,3]+0.07*x[6,4]+0.014*x[6,5]+0.06*x[6,7]+0.2*x[6,8]+0.5*x[6,9]
+0.8*x[7,0]+0.7*x[7,1]+0.6*x[7,2]+0.6*x[7,3]+0.07*x[7,4]+0.0185*x[7,5]+0.06*x[7,6]+ 0.1*x[7,8]+0.4*x[7,9]
+0.9*x[8,0]+0.8*x[8,1]+0.8*x[8,2]+0.8*x[8,3]+0.2*x[8,4]+0.1*x[8,5]+0.2*x[8,6]+0.1*x[8,7]+0.3*x[8,9]
+1.1*x[9,0]+1.1*x[9,1]+1*x[9,2]+x[9,3]+0.5*x[9,4]+0.4*x[9,5]+0.5*x[9,6]+0.4*x[9,7]+0.3*x[9,8]

constraints = []


constraints.append(x[0,0]==0)
constraints.append(x[1,1]==0)
constraints.append(x[2,2]==0)
constraints.append(x[3,3]==0)
constraints.append(x[4,4]==0)
constraints.append(x[5,5]==0)
constraints.append(x[6,6]==0)
constraints.append(x[7,7]==0)
constraints.append(x[8,8]==0)
constraints.append(x[9,9]==0)


#constraints.append(x[1,0]+x[1,2]+x[1,3]+x[1,4]+x[1,5]+x[1,6]+x[1,7]+x[1,8]+x[1,9]==1)
constraints.append(x[2,0]+x[2,5]+x[2,6]+x[2,8]==1)
#constraints.append(x[3,0]+x[3,1]+x[3,2]+x[3,4]+x[3,5]+x[3,6]+x[3,7]+x[3,8]+x[3,9]==1)
#constraints.append(x[4,0]+x[4,1]+x[4,2]+x[4,3]+x[4,5]+x[4,6]+x[4,7]+x[4,8]+x[4,9]==1)
constraints.append(x[5,0]+x[5,2]+x[5,6]+x[5,8]==1)
constraints.append(x[6,0]+x[6,2]+x[6,5]+x[6,8]==1)
#constraints.append(x[7,0]+x[7,1]+x[7,2]+x[7,3]+x[7,4]+x[7,5]+x[7,6]+x[7,8]+x[7,9]==1)
constraints.append(x[8,0]+x[8,2]+x[8,5]+x[8,6]==1)
#constraints.append(x[9,0]+x[9,1]+x[9,2]+x[9,3]+x[9,4]+x[9,5]+x[9,6]+x[9,7]+x[9,8]==1)
constraints.append(x[0,2]+x[0,5]+x[0,6]+x[0,8]==1)
constraints.append(x[2,0]+x[5,0]+x[6,0]+x[8,0]==1)
#constraints.append(x[0,1]+x[2,1]+x[3,1]+x[4,1]+x[5,1]+x[6,1]+x[7,1]+x[8,1]+x[9,1]==1)
constraints.append(x[0,2]+x[5,2]+x[6,2]+x[8,2]==1)
#constraints.append(x[0,3]+x[1,3]+x[2,3]+x[4,3]+x[5,3]+x[6,3]+x[7,3]+x[8,3]+x[9,3]==1)
#constraints.append(x[0,4]+x[1,4]+x[2,4]+x[3,4]+x[5,4]+x[6,4]+x[7,4]+x[8,4]+x[9,4]==1)
constraints.append(x[0,5]+x[2,5]+x[6,5]+x[8,5]==1)
constraints.append(x[0,6]+x[2,6]+x[5,6]+x[8,6]==1)
#constraints.append(x[0,7]+x[1,7]+x[2,7]+x[3,7]+x[4,7]+x[5,7]+x[6,7]+x[8,7]+x[9,7]==1)
constraints.append(x[0,8]+x[2,8]+x[5,8]+x[6,8]==1)
#constraints.append(x[0,9]+x[1,9]+x[2,9]+x[3,9]+x[4,9]+x[5,9]+x[6,9]+x[7,9]+x[8,9]==1)

constraints.append(y[0]-y[2]+10*x[0,2]<=9)
constraints.append(y[0]-y[5]+10*x[0,5]<=9)
constraints.append(y[0]-y[6]+10*x[0,6]<=9)
constraints.append(y[0]-y[8]+10*x[0,8]<=9)
#constraints.append(y[0]-y[9]+10*x[0,9]<=9)


#constraints.append(y[2]-y[7]+10*x[2,7]<=9)

constraints.append(y[2]-y[5]+10*x[2,5]<=9)
constraints.append(y[2]-y[6]+10*x[2,6]<=9)
constraints.append(y[2]-y[8]+10*x[2,8]<=9)
#constraints.append(y[2]-y[9]+10*x[2,9]<=9)

constraints.append(y[5]-y[6]+10*x[5,6]<=9)
#constraints.append(y[5]-y[7]+10*x[5,7]<=9)
constraints.append(y[5]-y[8]+10*x[5,8]<=9)
#constraints.append(y[5]-y[9]+10*x[5,9]<=9)

#constraints.append(y[6]-y[7]+10*x[6,7]<=9)
constraints.append(y[6]-y[8]+10*x[6,8]<=9)
#constraints.append(y[6]-y[9]+10*x[6,9]<=9)

#constraints.append(y[7]-y[8]+10*x[7,8]<=9)
#constraints.append(y[7]-y[9]+10*x[7,9]<=9)

#constraints.append(y[8]-y[9]+10*x[8,9]<=9)

for j in range(10):
    constraints.append(x[1,j]==0)
    constraints.append(x[3,j]==0)
    constraints.append(x[4,j]==0)
    constraints.append(x[7,j]==0)
    constraints.append(x[9,j]==0)
    
for i in range(10):
    constraints.append(x[i,1]==0)
    constraints.append(x[i,3]==0)
    constraints.append(x[i,4]==0)
    constraints.append(x[i,7]==0)
    constraints.append(x[i,9]==0)
    
problem = cp.Problem(cp.Minimize(obj_func), constraints)
problem.solve(solver=cp.GUROBI,verbose = False)
print("obj_func =")
print(obj_func.value)
print("x =")
print(x.value)





obj_func =
0.04
x =
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
import cvxpy as cp
  
y=cp.Variable(10,boolean=True)
x=cp.Variable(10,integer=True)
A=[3.67,4.67,3,4.67,4.67,5.33,7.33,7,4.33,5]
obj_func = cp.sum(cp.multiply(A,x))

constraints = []
   
#time constraint bars open at 9 pm and shut at 1 am. On average college students spend 2.5-4 hrs in bars on friday night",
constraints.append(23*y[0]+20*y[1]+25*y[2]+ 50*y[3]+35*y[4]+60*y[5]+ 57*y[6]+ 45*y[7]+ 30*y[8]+ 35*y[9]>=150)
constraints.append(23*y[0]+20*y[1]+25*y[2]+ 50*y[3]+35*y[4]+60*y[5]+ 57*y[6]+ 45*y[7]+ 30*y[8]+ 35*y[9]<=240)
   
#average rating constraint. 3.5<=rating<=5.0
constraints.append(0.9*y[0]+0.7*y[1]+0.8*y[2]+0.5*y[3]-0.4*y[4]+0.7*y[6]-0.6*y[7]+y[8]+y[9]>=0)
constraints.append(-0.6*y[0]-0.8*y[1]-0.7*y[2]-1*y[3]-1.9*y[4]-1.5*y[5]-0.8*y[6]-2.1*y[7]-0.5*y[8]-0.5*y[9]<=0)
constraints.append(x[0]<=10*y[0])
constraints.append(1*y[0]<=x[0])
constraints.append(x[1]<=10*y[1])
constraints.append(0<=x[1])
constraints.append(x[2]<=10*y[2])
constraints.append(0<=x[2])
constraints.append(x[3]<=10*y[3])
constraints.append(0<=x[3])
constraints.append(x[4]<=10*y[4])
constraints.append(0<=x[4])
constraints.append(x[5]<=10*y[5])
constraints.append(0<=x[5])
constraints.append(x[6]<=10*y[6])
constraints.append(0<=x[6])
constraints.append(x[7]<=10*y[7])
constraints.append(0<=x[7])
constraints.append(x[8]<=10*y[8])
constraints.append(0<=x[8])
constraints.append(x[9]<=10*y[9])
constraints.append(0<=x[9])

constraints.append(x[0]+x[1]+x[2]+x[3]+x[4]+x[5]+x[6]+x[7]+x[8]+x[9]<=20)
constraints.append(x[0]+x[1]+x[2]+x[3]+x[4]+x[5]+x[6]+x[7]+x[8]+x[9]>=7)
constraints.append(3.67*x[0]<=10)
constraints.append(4.67*x[1]<=10)
constraints.append(3*x[2]<=10)
constraints.append(4.67*x[3]<=10)
constraints.append(4.67*x[4]<=10)
constraints.append(5.33*x[5]<=10)
constraints.append(7.33*x[6]<=10)
constraints.append(7*x[7]<=10)
constraints.append(4.33*x[8]<=10)
constraints.append(5*x[9]<=10)

problem = cp.Problem(cp.Minimize(obj_func), constraints)
problem.solve(solver=cp.GUROBI,verbose = False)
print("obj_func =")
print(obj_func.value)
print("y =")
print(y.value)
print("x =")
print(x.value)

obj_func =
25.0
y =
[ 1. -0.  1. -0. -0.  1.  1. -0.  1. -0.]
x =
[ 2. -0.  3. -0. -0. -0. -0. -0.  2. -0.]


In [27]:

#constraints.append(x[1,0]+x[1,2]+x[1,3]+x[1,4]+x[1,5]+x[1,6]+x[1,7]+x[1,8]+x[1,9]==1)
constraints.append(x[2,0]+x[2,5]+x[2,6]+x[2,8]==1)
#constraints.append(x[3,0]+x[3,1]+x[3,2]+x[3,4]+x[3,5]+x[3,6]+x[3,7]+x[3,8]+x[3,9]==1)
#constraints.append(x[4,0]+x[4,1]+x[4,2]+x[4,3]+x[4,5]+x[4,6]+x[4,7]+x[4,8]+x[4,9]==1)
constraints.append(x[5,0]+x[5,2]+x[5,6]+x[5,8]==1)
constraints.append(x[6,0]+x[6,2]+x[6,5]+x[6,8]==1)
#constraints.append(x[7,0]+x[7,1]+x[7,2]+x[7,3]+x[7,4]+x[7,5]+x[7,6]+x[7,8]+x[7,9]==1)
constraints.append(x[8,0]+x[8,2]+x[8,5]+x[8,6]==1)
#constraints.append(x[9,0]+x[9,1]+x[9,2]+x[9,3]+x[9,4]+x[9,5]+x[9,6]+x[9,7]+x[9,8]==1)

constraints.append(x[2,0]+x[5,0]+x[6,0]+x[8,0]==1)
#constraints.append(x[0,1]+x[2,1]+x[3,1]+x[4,1]+x[5,1]+x[6,1]+x[7,1]+x[8,1]+x[9,1]==1)
constraints.append(x[0,2]+x[5,2]+x[6,2]+x[8,2]==1)
#constraints.append(x[0,3]+x[1,3]+x[2,3]+x[4,3]+x[5,3]+x[6,3]+x[7,3]+x[8,3]+x[9,3]==1)
#constraints.append(x[0,4]+x[1,4]+x[2,4]+x[3,4]+x[5,4]+x[6,4]+x[7,4]+x[8,4]+x[9,4]==1)
constraints.append(x[0,5]+x[2,5]+x[6,5]+x[8,5]==1)
constraints.append(x[0,6]+x[2,6]+x[5,6]+x[8,6]==1)
#constraints.append(x[0,7]+x[1,7]+x[2,7]+x[3,7]+x[4,7]+x[5,7]+x[6,7]+x[8,7]+x[9,7]==1)
constraints.append(x[0,8]+x[2,8]+x[5,8]+x[6,8]==1)
#constraints.append(x[0,9]+x[1,9]+x[2,9]+x[3,9]+x[4,9]+x[5,9]+x[6,9]+x[7,9]+x[8,9]==1)

IndexError: Too many indices for expression.